name: CheezSurvQuotes
version: '${project.version}'
main: io.github.seriousguy888.cheezsurvquotes.CheezSurvQuotes
api-version: 1.19
authors: [ SeriousGuy888 ]
description: "random actionbar messages"
commands:
  togglequotes:
    description: Toggle whether you will see quotes in your actionbar.